# coding: utf-8

"""
    QuePasa RAG SaaS API

    API for RAG retrieval, managing documents, files, and related operations including Telegram integration.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quepasa.models.operation_failed_status import OperationFailedStatus

class TestOperationFailedStatus(unittest.TestCase):
    """OperationFailedStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperationFailedStatus:
        """Test OperationFailedStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperationFailedStatus`
        """
        model = OperationFailedStatus()
        if include_optional:
            return OperationFailedStatus(
                status = ''
            )
        else:
            return OperationFailedStatus(
                status = '',
        )
        """

    def testOperationFailedStatus(self):
        """Test OperationFailedStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
