# coding: utf-8

"""
    QuePasa RAG SaaS API

    API for RAG retrieval, managing documents, files, and related operations including Telegram integration.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quepasa.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_batch_status(self) -> None:
        """Test case for get_batch_status

        Get batch status
        """
        pass

    def test_get_document(self) -> None:
        """Test case for get_document

        Get document details
        """
        pass

    def test_list_documents(self) -> None:
        """Test case for list_documents

        List documents
        """
        pass

    def test_remove_document(self) -> None:
        """Test case for remove_document

        Remove document
        """
        pass

    def test_replace_documents(self) -> None:
        """Test case for replace_documents

        Replace documents
        """
        pass

    def test_reset_documents(self) -> None:
        """Test case for reset_documents

        Reset documents
        """
        pass

    def test_setup_telegram(self) -> None:
        """Test case for setup_telegram

        Setup Telegram integration
        """
        pass

    def test_upsert_documents(self) -> None:
        """Test case for upsert_documents

        Upsert documents
        """
        pass

    def test_upsert_files(self) -> None:
        """Test case for upsert_files

        Upsert files
        """
        pass


if __name__ == '__main__':
    unittest.main()
