# coding: utf-8

"""
    QuePasa RAG SaaS API

    API for RAG retrieval, managing documents, files, and related operations including Telegram integration.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quepasa.models.created_batch_status_data import CreatedBatchStatusData

class TestCreatedBatchStatusData(unittest.TestCase):
    """CreatedBatchStatusData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatedBatchStatusData:
        """Test CreatedBatchStatusData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatedBatchStatusData`
        """
        model = CreatedBatchStatusData()
        if include_optional:
            return CreatedBatchStatusData(
                batch_id = '',
                processed_ids = [
                    ''
                    ]
            )
        else:
            return CreatedBatchStatusData(
        )
        """

    def testCreatedBatchStatusData(self):
        """Test CreatedBatchStatusData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
